In [2]:
import torch
import torch.distributions as dist

We are modeling the number of good days in a week.  
for instance: D = {4,5,6,1} means we sampled 4 weeks,  
first week had 4 good days, second week 5 etc..  

In [4]:
n_good_days = dist.Binomial(total_count=7, probs=0.7)
n_good_days.sample() # returns the number of good days in a week

tensor(6.)

In [7]:
D = n_good_days.sample((10,))

In [17]:
# probability of having no good days:
n_good_days.log_prob(torch.Tensor([0])).exp_()

tensor([0.0002])

In [18]:
# probability of having 7 good days
n_good_days.log_prob(torch.Tensor([7])).exp_()

tensor([0.0824])

In [19]:
# probability of having 5 good days
n_good_days.log_prob(torch.Tensor([5])).exp_()

tensor([0.3177])