In [1]:
import numpy as np

In [2]:
dataset_x = np.random.rand(10)
theta = 0.7
dataset_x

array([0.12029628, 0.48743076, 0.67010686, 0.98442624, 0.712319  ,
       0.11718065, 0.3406401 , 0.50811375, 0.20934969, 0.54495761])

In [6]:
(dataset_x <= theta).astype(int)

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1])

In [7]:
def sample_bernoulli(theta, n_samples):
    return (np.random.rand(n_samples) <= theta).astype(int)

In [15]:
sample_bernoulli(theta, 10)

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [16]:
import torch
import torch.distributions as dist

In [18]:
# this is the same but uses pytorch
x = dist.Bernoulli(probs=theta).sample((100,))

In [23]:
# so is this, but this uses np
np.random.binomial(1, p=theta, size=100)
np.random.binomial()

TypeError: binomial() takes at least 2 positional arguments (0 given)